# Generated by Django 5.0.4 on 2024-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('dept', models.CharField(max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
